### ISSUE TITLE
panic: runtime error: integer divide by zero

### ISSUE THREAD

**Issue by mgerasimchuk** [fdaines/arch-go#26]
The full reproducing scenario is bellow:

```
» docker run --rm -w /app -it golang:1.18.0 /bin/bash     
root@aab9a988627e:/app# go install github.com/fdaines/arch-go@v1.4.2
go: downloading github.com/fdaines/arch-go v1.4.2
.....
root@aab9a988627e:/app# mkdir -p internal/domain
root@aab9a988627e:/app# echo -e "package domain\n type Model struct {}" > internal/domain/model.go
root@aab9a988627e:/app# echo -e "version: 1\ndependenciesRules:\n- package: '**.internal/domain.**'\n  shouldOnlyDependsOn:\n    internal:\n    - '**.internal/domain.**'" > arch-go.yml
root@aab9a988627e:/app# cat arch-go.yml 
version: 1
dependenciesRules:
- package: '**.internal/domain.**'
  shouldOnlyDependsOn:
    internal:
    - '**.internal/domain.**'
root@aab9a988627e:/app# arch-go -v
Looking for packages.
1 packages found...
Loading package (1/1): ./...
[PASS] - Packages matching pattern '**.internal/domain.**' should ['only depend on internal packages that matches [[**.internal/domain.**]]']
panic: runtime error: integer divide by zero

goroutine 1 [running]:
github.com/fdaines/arch-go/internal/model/result.resolveCoverageThreshold(0x40002a59b0, 0x40000b2240, {0x4000054460?, 0xf?, 0x10?}, {0x0, 0x0, 0x11?})
        /go/pkg/mod/github.com/fdaines/arch-go@v1.4.2/internal/model/result/result_summary.go:65 +0x234
github.com/fdaines/arch-go/internal/model/result.ResolveRulesSummary({0x0, 0x0, 0x0}, {0x4000054460, 0x1, 0x1}, 0x40000b2240)
        /go/pkg/mod/github.com/fdaines/arch-go@v1.4.2/internal/model/result/result_summary.go:31 +0x204
github.com/fdaines/arch-go/internal/model/result.ResolveReport(...)
        /go/pkg/mod/github.com/fdaines/arch-go@v1.4.2/internal/model/result/result.go:12
github.com/fdaines/arch-go/internal/impl.CheckArchitecture.func1()
        /go/pkg/mod/github.com/fdaines/arch-go@v1.4.2/internal/impl/rule_runner.go:46 +0x144
github.com/fdaines/arch-go/internal/utils.ExecuteWithTimer(0x40000e5d08)
        /go/pkg/mod/github.com/fdaines/arch-go@v1.4.2/internal/utils/timer_functions.go:12 +0x3c
github.com/fdaines/arch-go/internal/impl.CheckArchitecture()
        /go/pkg/mod/github.com/fdaines/arch-go@v1.4.2/internal/impl/rule_runner.go:25 +0x44
github.com/fdaines/arch-go/internal/cmd.runCommand(0x644200?, {0x37e76d?, 0x1?, 0x1?})
        /go/pkg/mod/github.com/fdaines/arch-go@v1.4.2/internal/cmd/root.go:35 +0x20
github.com/spf13/cobra.(*Command).execute(0x644200, {0x40000ba010, 0x1, 0x1})
        /go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:920 +0x5f4
github.com/spf13/cobra.(*Command).ExecuteC(0x644200)
        /go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:1040 +0x360
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:968
github.com/fdaines/arch-go/internal/cmd.Execute()
        /go/pkg/mod/github.com/fdaines/arch-go@v1.4.2/internal/cmd/root.go:24 +0x2c
main.main()
        /go/pkg/mod/github.com/fdaines/arch-go@v1.4.2/main.go:8 +0x20
root@aab9a988627e:/app#
```

It relates to this line: https://github.com/fdaines/arch-go/blob/v1.4.2/internal/model/result/result_summary.go#L65

And it reproducing only on tiny projects

**Comment by fdaines** [comment]
Sorry the delay, I'll check it and try to solve it.

**Comment by fdaines** [comment]
@mgerasimchuk , Arch-Go works with Go Modules, so you need to init your project as a Module and then run arch-go.

```
$ go mod init foobar
$ arch-go -v
```

**Comment by mgerasimchuk** [comment]
@fdaines sorry for the false-positive issue and thank you for the clarification, I double checked and you are right - with modules all works correctly:
```
» ~  docker run --rm -w /app -it golang:1.18.0 /bin/bash
root@25befddcc46c:/app# go install github.com/fdaines/arch-go@v1.4.2
go: downloading github.com/fdaines/arch-go v1.4.2
go: downloading github.com/spf13/cobra v1.6.0
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/fatih/color v1.13.0
go: downloading github.com/jedib0t/go-pretty/v6 v6.4.0
go: downloading golang.org/x/mod v0.6.0
go: downloading golang.org/x/tools v0.1.12
go: downloading github.com/mattn/go-isatty v0.0.16
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/mattn/go-runewidth v0.0.14
go: downloading golang.org/x/sys v0.1.0
go: downloading github.com/rivo/uniseg v0.4.2
mkdir -p internal/domainroot@25befddcc46c:/app# mkdir -p internal/domain
root@25befddcc46c:/app# echo -e "package domain\n type Model struct {}" > internal/domain/model.go
root@25befddcc46c:/app# echo -e "version: 1\ndependenciesRules:\n- package: '**.internal/domain.**'\n  shouldOnlyDependsOn:\n    internal:\n    - '**.internal/domain.**'" > arch-go.yml
root@25befddcc46c:/app# cat arch-go.yml 
version: 1
dependenciesRules:
- package: '**.internal/domain.**'
  shouldOnlyDependsOn:
    internal:
    - '**.internal/domain.**'
root@25befddcc46c:/app# arch-go -v
Looking for packages.
1 packages found...
Loading package (1/1): ./...
[PASS] - Packages matching pattern '**.internal/domain.**' should ['only depend on internal packages that matches [[**.internal/domain.**]]']
panic: runtime error: integer divide by zero

goroutine 1 [running]:
github.com/fdaines/arch-go/internal/model/result.resolveCoverageThreshold(0x40002659b0, 0x40000142d0, {0x4000214520?, 0xf?, 0x10?}, {0x0, 0x0, 0x11?})
	/go/pkg/mod/github.com/fdaines/arch-go@v1.4.2/internal/model/result/result_summary.go:65 +0x234
github.com/fdaines/arch-go/internal/model/result.ResolveRulesSummary({0x0, 0x0, 0x0}, {0x4000214520, 0x1, 0x1}, 0x40000142d0)
	/go/pkg/mod/github.com/fdaines/arch-go@v1.4.2/internal/model/result/result_summary.go:31 +0x204
github.com/fdaines/arch-go/internal/model/result.ResolveReport(...)
	/go/pkg/mod/github.com/fdaines/arch-go@v1.4.2/internal/model/result/result.go:12
github.com/fdaines/arch-go/internal/impl.CheckArchitecture.func1()
	/go/pkg/mod/github.com/fdaines/arch-go@v1.4.2/internal/impl/rule_runner.go:46 +0x144
github.com/fdaines/arch-go/internal/utils.ExecuteWithTimer(0x4000137d08)
	/go/pkg/mod/github.com/fdaines/arch-go@v1.4.2/internal/utils/timer_functions.go:12 +0x3c
github.com/fdaines/arch-go/internal/impl.CheckArchitecture()
	/go/pkg/mod/github.com/fdaines/arch-go@v1.4.2/internal/impl/rule_runner.go:25 +0x44
github.com/fdaines/arch-go/internal/cmd.runCommand(0x644200?, {0x37e76d?, 0x1?, 0x1?})
	/go/pkg/mod/github.com/fdaines/arch-go@v1.4.2/internal/cmd/root.go:35 +0x20
github.com/spf13/cobra.(*Command).execute(0x644200, {0x4000012050, 0x1, 0x1})
	/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:920 +0x5f4
github.com/spf13/cobra.(*Command).ExecuteC(0x644200)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:1040 +0x360
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:968
github.com/fdaines/arch-go/internal/cmd.Execute()
	/go/pkg/mod/github.com/fdaines/arch-go@v1.4.2/internal/cmd/root.go:24 +0x2c
main.main()
	/go/pkg/mod/github.com/fdaines/arch-go@v1.4.2/main.go:8 +0x20
root@25befddcc46c:/app# go mod init foobar
go: creating new go.mod: module foobar
go: to add module requirements and sums:
	go mod tidy
root@25befddcc46c:/app# go mod tidy
root@25befddcc46c:/app# arch-go -v
Looking for packages.
1 packages found...
Loading package (1/1): foobar/internal/domain
Checking dependency rules for package: foobar/internal/domain
[PASS] - Packages matching pattern '**.internal/domain.**' should ['only depend on internal packages that matches [[**.internal/domain.**]]']
	Package 'foobar/internal/domain' passes
+---+-----------------+-------------+-------------+-------------+
| # | RULE TYPE       |       TOTAL |   SUCCEEDED |      FAILED |
+---+-----------------+-------------+-------------+-------------+
| 1 | Content Rule    |           0 |           0 |           0 |
| 2 | Dependency Rule |           1 |           1 |           0 |
| 3 | Function Rule   |           0 |           0 |           0 |
| 4 | Naming Rule     |           0 |           0 |           0 |
+---+-----------------+-------------+-------------+-------------+
|   | COMPLIANCE RATE | 100% [PASS]                             |
|   | COVERAGE RATE   | 100% [PASS]                             |
+---+-----------------+-----------------------------------------+
--------------------------------------
	Execution Summary
--------------------------------------
Total Rules: 	1
Succeeded: 	1
Failed: 	0
--------------------------------------
Compliance:      100% (Pass)
Coverage:        100% (Pass)
Time: 0.036 seconds
root@25befddcc46c:/app# 
```

**Comment by fdaines** [comment]
Great!, don't worry about the false positive, I'm sure that it will be useful for other people as workaround.
Best Regards!
